### ISSUE TITLE
Base64Decoder().convert() throws exception when validating token

### ISSUE THREAD

**Issue by twast92** [effortless-mgmt/ems_app#153]
Exception message: 

> Invalid length, must be multiple of four

Tokens can be of a length that is not a multiple of four.
Pls fix the backend so this isn't the case.
kthxbye

**Comment by algorythm** [comment]
JWS standard defines that the padding should **not** be included: <https://tools.ietf.org/html/rfc7515#section-2>.

See dotnet/core#2235.

**Comment by algorythm** [comment]
Re-opened as the issue is still an issue, which has to be fixed client side. The error is not on the backend, but the app.
